spring:
  application:
    name: failover-demo
  h2:
    console:
      enabled: true

failover:
  enabled: true
  store:
    type: jdbc
    jdbc:
      table-prefix: DEMO_

management:
  endpoints:
    web:
      exposure:
        # Exposes common metrics and the Prometheus endpoint
        include: "health, metrics, prometheus"
  endpoint:
    health:
      show-details: always # Shows detailed subsystem health status
    metrics:
      enabled: true
    prometheus:
      enabled: true